// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
// @ts-nocheck
import {
  AlgebraicType,
  AlgebraicValue,
  BinaryReader,
  BinaryWriter,
  CallReducerFlags,
  ConnectionId,
  DbConnectionBuilder,
  DbConnectionImpl,
  DbContext,
  ErrorContextInterface,
  Event,
  EventContextInterface,
  Identity,
  ProductType,
  ProductTypeElement,
  ReducerEventContextInterface,
  SubscriptionBuilderImpl,
  SubscriptionEventContextInterface,
  SumType,
  SumTypeVariant,
  TableCache,
  TimeDuration,
  Timestamp,
  deepEqual,
} from "@clockworklabs/spacetimedb-sdk";
import { Bit } from "./bit_type";
import { Color as __Color } from "./color_type";

import { EventContext, Reducer, RemoteReducers, RemoteTables } from ".";

/**
 * Table handle for the table `bit`.
 *
 * Obtain a handle from the [`bit`] property on [`RemoteTables`],
 * like `ctx.db.bit`.
 *
 * Users are encouraged not to explicitly reference this type,
 * but to directly chain method calls,
 * like `ctx.db.bit.on_insert(...)`.
 */
export class BitTableHandle {
  tableCache: TableCache<Bit>;

  constructor(tableCache: TableCache<Bit>) {
    this.tableCache = tableCache;
  }

  count(): number {
    return this.tableCache.count();
  }

  iter(): Iterable<Bit> {
    return this.tableCache.iter();
  }
  /**
   * Access to the `bitId` unique index on the table `bit`,
   * which allows point queries on the field of the same name
   * via the [`BitBitIdUnique.find`] method.
   *
   * Users are encouraged not to explicitly reference this type,
   * but to directly chain method calls,
   * like `ctx.db.bit.bitId().find(...)`.
   *
   * Get a handle on the `bitId` unique index on the table `bit`.
   */
  bitId = {
    // Find the subscribed row whose `bitId` column value is equal to `col_val`,
    // if such a row is present in the client cache.
    find: (col_val: bigint): Bit | undefined => {
      for (let row of this.tableCache.iter()) {
        if (deepEqual(row.bitId, col_val)) {
          return row;
        }
      }
    },
  };

  onInsert = (cb: (ctx: EventContext, row: Bit) => void) => {
    return this.tableCache.onInsert(cb);
  }

  removeOnInsert = (cb: (ctx: EventContext, row: Bit) => void) => {
    return this.tableCache.removeOnInsert(cb);
  }

  onDelete = (cb: (ctx: EventContext, row: Bit) => void) => {
    return this.tableCache.onDelete(cb);
  }

  removeOnDelete = (cb: (ctx: EventContext, row: Bit) => void) => {
    return this.tableCache.removeOnDelete(cb);
  }

  // Updates are only defined for tables with primary keys.
  onUpdate = (cb: (ctx: EventContext, oldRow: Bit, newRow: Bit) => void) => {
    return this.tableCache.onUpdate(cb);
  }

  removeOnUpdate = (cb: (ctx: EventContext, onRow: Bit, newRow: Bit) => void) => {
    return this.tableCache.removeOnUpdate(cb);
  }}
