// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
// @ts-nocheck
import {
  AlgebraicType,
  AlgebraicValue,
  BinaryReader,
  BinaryWriter,
  CallReducerFlags,
  ConnectionId,
  DbConnectionBuilder,
  DbConnectionImpl,
  DbContext,
  ErrorContextInterface,
  Event,
  EventContextInterface,
  Identity,
  ProductType,
  ProductTypeElement,
  ReducerEventContextInterface,
  SubscriptionBuilderImpl,
  SubscriptionEventContextInterface,
  SumType,
  SumTypeVariant,
  TableCache,
  TimeDuration,
  Timestamp,
  deepEqual,
} from "@clockworklabs/spacetimedb-sdk";
import { Color as __Color } from "./color_type";
import { Direction as __Direction } from "./direction_type";

export type Bot = {
  botId: bigint,
  x: number,
  y: number,
  dx: number,
  dy: number,
  direction: __Direction | undefined,
  color: __Color,
  health: number,
  size: number,
};

/**
 * A namespace for generated helper functions.
 */
export namespace Bot {
  /**
  * A function which returns this type represented as an AlgebraicType.
  * This function is derived from the AlgebraicType used to generate this type.
  */
  export function getTypeScriptAlgebraicType(): AlgebraicType {
    return AlgebraicType.createProductType([
      new ProductTypeElement("botId", AlgebraicType.createU64Type()),
      new ProductTypeElement("x", AlgebraicType.createI32Type()),
      new ProductTypeElement("y", AlgebraicType.createI32Type()),
      new ProductTypeElement("dx", AlgebraicType.createF32Type()),
      new ProductTypeElement("dy", AlgebraicType.createF32Type()),
      new ProductTypeElement("direction", AlgebraicType.createOptionType(__Direction.getTypeScriptAlgebraicType())),
      new ProductTypeElement("color", __Color.getTypeScriptAlgebraicType()),
      new ProductTypeElement("health", AlgebraicType.createF32Type()),
      new ProductTypeElement("size", AlgebraicType.createF32Type()),
    ]);
  }

  export function serialize(writer: BinaryWriter, value: Bot): void {
    Bot.getTypeScriptAlgebraicType().serialize(writer, value);
  }

  export function deserialize(reader: BinaryReader): Bot {
    return Bot.getTypeScriptAlgebraicType().deserialize(reader);
  }

}


