// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
// @ts-nocheck
import {
  AlgebraicType,
  AlgebraicValue,
  BinaryReader,
  BinaryWriter,
  CallReducerFlags,
  ConnectionId,
  DbConnectionBuilder,
  DbConnectionImpl,
  DbContext,
  ErrorContextInterface,
  Event,
  EventContextInterface,
  Identity,
  ProductType,
  ProductTypeElement,
  ReducerEventContextInterface,
  SubscriptionBuilderImpl,
  SubscriptionEventContextInterface,
  SumType,
  SumTypeVariant,
  TableCache,
  TimeDuration,
  Timestamp,
  deepEqual,
} from "@clockworklabs/spacetimedb-sdk";
import { Bot } from "./bot_type";
import { Color as __Color } from "./color_type";

import { EventContext, Reducer, RemoteReducers, RemoteTables } from ".";

/**
 * Table handle for the table `bot`.
 *
 * Obtain a handle from the [`bot`] property on [`RemoteTables`],
 * like `ctx.db.bot`.
 *
 * Users are encouraged not to explicitly reference this type,
 * but to directly chain method calls,
 * like `ctx.db.bot.on_insert(...)`.
 */
export class BotTableHandle {
  tableCache: TableCache<Bot>;

  constructor(tableCache: TableCache<Bot>) {
    this.tableCache = tableCache;
  }

  count(): number {
    return this.tableCache.count();
  }

  iter(): Iterable<Bot> {
    return this.tableCache.iter();
  }
  /**
   * Access to the `botId` unique index on the table `bot`,
   * which allows point queries on the field of the same name
   * via the [`BotBotIdUnique.find`] method.
   *
   * Users are encouraged not to explicitly reference this type,
   * but to directly chain method calls,
   * like `ctx.db.bot.botId().find(...)`.
   *
   * Get a handle on the `botId` unique index on the table `bot`.
   */
  botId = {
    // Find the subscribed row whose `botId` column value is equal to `col_val`,
    // if such a row is present in the client cache.
    find: (col_val: bigint): Bot | undefined => {
      for (let row of this.tableCache.iter()) {
        if (deepEqual(row.botId, col_val)) {
          return row;
        }
      }
    },
  };

  onInsert = (cb: (ctx: EventContext, row: Bot) => void) => {
    return this.tableCache.onInsert(cb);
  }

  removeOnInsert = (cb: (ctx: EventContext, row: Bot) => void) => {
    return this.tableCache.removeOnInsert(cb);
  }

  onDelete = (cb: (ctx: EventContext, row: Bot) => void) => {
    return this.tableCache.onDelete(cb);
  }

  removeOnDelete = (cb: (ctx: EventContext, row: Bot) => void) => {
    return this.tableCache.removeOnDelete(cb);
  }

  // Updates are only defined for tables with primary keys.
  onUpdate = (cb: (ctx: EventContext, oldRow: Bot, newRow: Bot) => void) => {
    return this.tableCache.onUpdate(cb);
  }

  removeOnUpdate = (cb: (ctx: EventContext, onRow: Bot, newRow: Bot) => void) => {
    return this.tableCache.removeOnUpdate(cb);
  }}
