// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
// @ts-nocheck
import {
  AlgebraicType,
  AlgebraicValue,
  BinaryReader,
  BinaryWriter,
  CallReducerFlags,
  ConnectionId,
  DbConnectionBuilder,
  DbConnectionImpl,
  DbContext,
  ErrorContextInterface,
  Event,
  EventContextInterface,
  Identity,
  ProductType,
  ProductTypeElement,
  ReducerEventContextInterface,
  SubscriptionBuilderImpl,
  SubscriptionEventContextInterface,
  SumType,
  SumTypeVariant,
  TableCache,
  TimeDuration,
  Timestamp,
  deepEqual,
} from "@clockworklabs/spacetimedb-sdk";
import { Moon } from "./moon_type";
import { Color as __Color } from "./color_type";

import { EventContext, Reducer, RemoteReducers, RemoteTables } from ".";

/**
 * Table handle for the table `moon`.
 *
 * Obtain a handle from the [`moon`] property on [`RemoteTables`],
 * like `ctx.db.moon`.
 *
 * Users are encouraged not to explicitly reference this type,
 * but to directly chain method calls,
 * like `ctx.db.moon.on_insert(...)`.
 */
export class MoonTableHandle {
  tableCache: TableCache<Moon>;

  constructor(tableCache: TableCache<Moon>) {
    this.tableCache = tableCache;
  }

  count(): number {
    return this.tableCache.count();
  }

  iter(): Iterable<Moon> {
    return this.tableCache.iter();
  }
  /**
   * Access to the `moonId` unique index on the table `moon`,
   * which allows point queries on the field of the same name
   * via the [`MoonMoonIdUnique.find`] method.
   *
   * Users are encouraged not to explicitly reference this type,
   * but to directly chain method calls,
   * like `ctx.db.moon.moonId().find(...)`.
   *
   * Get a handle on the `moonId` unique index on the table `moon`.
   */
  moonId = {
    // Find the subscribed row whose `moonId` column value is equal to `col_val`,
    // if such a row is present in the client cache.
    find: (col_val: bigint): Moon | undefined => {
      for (let row of this.tableCache.iter()) {
        if (deepEqual(row.moonId, col_val)) {
          return row;
        }
      }
    },
  };

  onInsert = (cb: (ctx: EventContext, row: Moon) => void) => {
    return this.tableCache.onInsert(cb);
  }

  removeOnInsert = (cb: (ctx: EventContext, row: Moon) => void) => {
    return this.tableCache.removeOnInsert(cb);
  }

  onDelete = (cb: (ctx: EventContext, row: Moon) => void) => {
    return this.tableCache.onDelete(cb);
  }

  removeOnDelete = (cb: (ctx: EventContext, row: Moon) => void) => {
    return this.tableCache.removeOnDelete(cb);
  }

  // Updates are only defined for tables with primary keys.
  onUpdate = (cb: (ctx: EventContext, oldRow: Moon, newRow: Moon) => void) => {
    return this.tableCache.onUpdate(cb);
  }

  removeOnUpdate = (cb: (ctx: EventContext, onRow: Moon, newRow: Moon) => void) => {
    return this.tableCache.removeOnUpdate(cb);
  }}
