// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

// This was generated using spacetimedb cli version 1.2.0 (commit fb41e50eb73573b70eea532aeb6158eaac06fae0).

/* eslint-disable */
/* tslint:disable */
// @ts-nocheck
import {
	AlgebraicType,
	AlgebraicValue,
	BinaryReader,
	BinaryWriter,
	ConnectionId,
	DbConnectionBuilder,
	DbConnectionImpl,
	Identity,
	ProductType,
	ProductTypeElement,
	SubscriptionBuilderImpl,
	SumType,
	SumTypeVariant,
	TableCache,
	TimeDuration,
	Timestamp,
	deepEqual,
	type CallReducerFlags,
	type DbContext,
	type ErrorContextInterface,
	type Event,
	type EventContextInterface,
	type ReducerEventContextInterface,
	type SubscriptionEventContextInterface,
} from "@clockworklabs/spacetimedb-sdk";

import { Color as __Color } from "./color_type";

export type SetUserMeta = {
	username: string;
	color: __Color;
	seed: bigint;
};

/**
 * A namespace for generated helper functions.
 */
export namespace SetUserMeta {
	/**
	 * A function which returns this type represented as an AlgebraicType.
	 * This function is derived from the AlgebraicType used to generate this type.
	 */
	export function getTypeScriptAlgebraicType(): AlgebraicType {
		return AlgebraicType.createProductType([
			new ProductTypeElement("username", AlgebraicType.createStringType()),
			new ProductTypeElement("color", __Color.getTypeScriptAlgebraicType()),
			new ProductTypeElement("seed", AlgebraicType.createU64Type()),
		]);
	}

	export function serialize(writer: BinaryWriter, value: SetUserMeta): void {
		SetUserMeta.getTypeScriptAlgebraicType().serialize(writer, value);
	}

	export function deserialize(reader: BinaryReader): SetUserMeta {
		return SetUserMeta.getTypeScriptAlgebraicType().deserialize(reader);
	}
}
