// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
// @ts-nocheck
import {
  AlgebraicType,
  AlgebraicValue,
  BinaryReader,
  BinaryWriter,
  CallReducerFlags,
  ConnectionId,
  DbConnectionBuilder,
  DbConnectionImpl,
  DbContext,
  ErrorContextInterface,
  Event,
  EventContextInterface,
  Identity,
  ProductType,
  ProductTypeElement,
  ReducerEventContextInterface,
  SubscriptionBuilderImpl,
  SubscriptionEventContextInterface,
  SumType,
  SumTypeVariant,
  TableCache,
  TimeDuration,
  Timestamp,
  deepEqual,
} from "@clockworklabs/spacetimedb-sdk";
import { Color as __Color } from "./color_type";

export type User = {
  identity: Identity,
  online: boolean,
  x: number,
  y: number,
  dx: number,
  dy: number,
  dirVecX: number,
  dirVecY: number,
  color: __Color,
  health: number,
  size: number,
  totalMoonSizeOribiting: number,
};

/**
 * A namespace for generated helper functions.
 */
export namespace User {
  /**
  * A function which returns this type represented as an AlgebraicType.
  * This function is derived from the AlgebraicType used to generate this type.
  */
  export function getTypeScriptAlgebraicType(): AlgebraicType {
    return AlgebraicType.createProductType([
      new ProductTypeElement("identity", AlgebraicType.createIdentityType()),
      new ProductTypeElement("online", AlgebraicType.createBoolType()),
      new ProductTypeElement("x", AlgebraicType.createF32Type()),
      new ProductTypeElement("y", AlgebraicType.createF32Type()),
      new ProductTypeElement("dx", AlgebraicType.createF32Type()),
      new ProductTypeElement("dy", AlgebraicType.createF32Type()),
      new ProductTypeElement("dirVecX", AlgebraicType.createF32Type()),
      new ProductTypeElement("dirVecY", AlgebraicType.createF32Type()),
      new ProductTypeElement("color", __Color.getTypeScriptAlgebraicType()),
      new ProductTypeElement("health", AlgebraicType.createF32Type()),
      new ProductTypeElement("size", AlgebraicType.createF32Type()),
      new ProductTypeElement("totalMoonSizeOribiting", AlgebraicType.createF32Type()),
    ]);
  }

  export function serialize(writer: BinaryWriter, value: User): void {
    User.getTypeScriptAlgebraicType().serialize(writer, value);
  }

  export function deserialize(reader: BinaryReader): User {
    return User.getTypeScriptAlgebraicType().deserialize(reader);
  }

}


