#!/bin/sh

echo "Setting up git hooks..."

cd client
echo "Linting..."
npm run lint

cd ..

cd server
cargo clippy --all-targets --all-features -- -D warnings
cargo fmt --all

if ! git diff --quiet; then
  echo "Linting made changes. Please stage the changes and try again."
  exit 1
fi

exit 0
